### ISSUE TITLE
Full example of dropdown is needed

### ISSUE THREAD

**Issue by kapooostin** [jessy1092/react-semantify#15]
Please, show some examples of how to use it. I checked the source and tests, and still I do not understand how to create all the different types of SUI dropdowns. Nothing I tried so far is working.

**Comment by jessy1092** [comment]
@kapooostin Hi, I create the [Dropdown page](http://jessy1092.github.io/react-semantify/#/Dropdown) to describe the properties in react-semantify. You can click `</>` to see the source. If you want to see the whole page source, you can see [here](https://github.com/jessy1092/react-semantify/blob/website/src/pages/DropdownPage.jsx).

The central idea of react-semantify is abridge className.

The origin dropdown usage in Semantic-UI with react.
```html
<div className="ui simple active dropdown">
    <div className="text">Dropdown</div>
    <i className="dropdown icon"></i>
    <div className="menu">
      <div className="item">Choice 1</div>
      <div className="item">Choice 2</div>
    </div>
  </div>
```
In react-semantify
```html
<Dropdown active={true}>
	<Text>Dropdown</Text>
	<Icon className="dropdown"/>
	<Menu>
		<Item>Choice 1</Item>
		<Item>Choice 2</Item>
	</Menu>
</Dropdown>
```
The `Dropdown`, `Text`, `Icon`, `Menu`, `Item` is the default components in react-semantify.

You can see more components in [here](https://github.com/jessy1092/react-semantify#component).

I don't know whether it is enough for you. If you have any question, welcome to ask. :+1:

**Comment by kapooostin** [comment]
Thank you! Now it works, finally.

Do I use Checkbox correctly?
```
<Checkbox>
    <input
        type="checkbox"
        checked={ checked }
        onChange={ this.onChange }
    />
    <label>{ displayName }</label>
</Checkbox>
```

**Comment by kapooostin** [comment]
Thank you! Now it works, finally.

Do I use Checkbox correctly?

```jsx
<Checkbox>
    <input
        type="checkbox"
        checked={ checked }
        onChange={ this.onChange }
    />
    <label>{ displayName }</label>
</Checkbox>
```

**Comment by jessy1092** [comment]
@kapooostin 
Yap, checkbox is used as same as [Semantic-UI description](http://semantic-ui.com/modules/checkbox.html). It is the simple use.

If you want checkbox initialize, you should add init={true} on Checkbox component. 
Let Checkbox can be worked.
like.
```html
<Checkbox init={true}>
    <input
        type="checkbox"
        checked={ checked }
        onChange={ this.onChange }
    />
    <label>{ displayName }</label>
</Checkbox>
```

BTW, Semantify's Checkbox component also wrap state with props. You can see [Checkbox Page](http://jessy1092.github.io/react-semantify/#/Checkbox) for more detail.

**Comment by jessy1092** [comment]
I think this issue could be closed. If you have any question, welcome to ask.
