### ISSUE TITLE
React included twice

### ISSUE THREAD

**Issue by serkanyersen** [jessy1092/react-semantify#16]
`react-semantify` installs react during `npm install`. My project also requires `react`, for some reason this causes two react to be included in the browserify build and application never starts. I have to remove the installed `react` from `npm_modules` of `react-semantify` to be able to run the application.

`rm -rf node_modules/react-semantify/node_modules/react` to be more precise.

If I use the same version as `react-semantify` application won't break but I still see the **Download the React DevTools for a better development experience:** message twice.

You can try this by checking out this application[1] and running `npm install` then `grunt server` application won't start unless you remove the react.

This is the error I'm getting
```
Download the React DevTools for a better development experience: http://fb.me/react-devtools app.js:7130
Download the React DevTools for a better development experience: http://fb.me/react-devtools app.js:22715
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory app.js:42363
Warning: Segment(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component. app.js:22715
Warning: Don't set the props property of the component. Mutate the existing props object instead. app.js:29069
Uncaught TypeError: Can't add property context, object is not extensible
```

Thanks for such a great tool btw
[1] - https://github.com/serkanyersen/tip

**Comment by jessy1092** [comment]
@serkanyersen Thanks for reporting and usage. I would update react version after confirm the react API change. It would release in v0.3.x. :+1:

**Comment by jessy1092** [comment]
Resolve on react-sematify v0.3.0
