### ISSUE TITLE
Compatibility with React 0.13

### ISSUE THREAD

**Issue by FoxxMD** [jessy1092/react-semantify#17]
I can't use any react-semantify components with React 0.13. My app breaks when using any component with the warnings:
* Column(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.
* Warning: Don't set the props property of the component. Mutate the existing props object instead.

And breaks with the message: `Can't add property context, object is not extensible`. I think this may happen because `props` can no longer be mutated?

Trace
```
ReactCompositeComponentMixin.mountComponent  ReactCompositeComponent.js?:153
ReactPerf.measure.wrapper                                        ReactPerf.js?70 
ReactReconciler.mountComponent                             ReactReconciler.js?38
```

**Comment by jessy1092** [comment]
@FoxxMD I release react-semantify 0.3.0 with React v0.13.x. Could you help to check whether it solves this problem? Thanks a lot.

**Comment by FoxxMD** [comment]
Yes I will test this tomorrow, thank you!

**Comment by FoxxMD** [comment]
This fixed it :+1:  thank you
