### ISSUE TITLE
Rating maybe have a bug

### ISSUE THREAD

**Issue by tonylinyy** [jessy1092/react-semantify#18]
Hi,thanks for the great job.
when i write the code according to the doc,but it does't work:
```<Rating init={{rating: 3, maxRating: 5}}></Rating>```
I try another way,it works:
```<Rating init={{initialRating: 3, maxRating: 5}}></Rating>```

**Comment by jessy1092** [comment]
@tonylinyy Thanks for report. I think it is the document error. I saw the [Semantic-UI](http://semantic-ui.com/modules/rating.html#/usage) writing the same way. 

I'm sorry for I didn't double check.

`<Rating init={{initialRating: 3, maxRating: 5}}></Rating>` is the right way.

I also create the [web document](http://jessy1092.github.io/react-semantify/#/Rating) for rating.
FYI, and welcome feedback.
