### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by sgentile** [jessy1092/react-semantify#22]
I'm getting errors using the modal, ie.

```
viewDetails(){
      $('.ui modal').modal('show');
    }
```

Uncaught TypeError: _$2.default(...).modal is not a functionviewDetails @ Episode.jsx?5999:21(anonymous function) @ makeAssimilatePrototype.js:15executeDispatch @ EventPluginUtils.js:110SimpleEventPlugin.executeDispatch @ SimpleEventPlugin.js:305forEachEventDispatch @ EventPluginUtils.js:98executeDispatchesInOrder @ EventPluginUtils.js:119executeDispatchesAndRelease @ EventPluginHub.js:46forEachAccumulated @ forEachAccumulated.js:23EventPluginHub.processEventQueue @ EventPluginHub.js:253runEventQueueInBatch @ ReactEventEmitterMixin.js:18ReactEventEmitterMixin.handleTopLevel @ ReactEventEmitterMixin.js:44handleTopLevelImpl @ ReactEventListener.js:80Mixin.perform @ Transaction.js:134ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:66batchedUpdates @ ReactUpdates.js:110ReactEventListener.dispatchEvent @ ReactEventListener.js:174

**Comment by jessy1092** [comment]
Hi @sgentile ,

Did you include or bundle semantic.js ?

```
_$2.default(...).modal is not a function
```
Look like modal function cannot be found.
