### ISSUE TITLE
Support Semantic-UI 2.0 new component

### ISSUE THREAD

**Issue by jessy1092** [jessy1092/react-semantify#24]
- [x] [Container](http://semantic-ui.com/elements/container.html)
- [x] [Embed](http://semantic-ui.com/modules/embed.html)
- [ ] Dropdown has new type: Multiselect

Release Note: https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md#version-200---june-30-2015

**Comment by contra** [comment]
Need help with this?

**Comment by jessy1092** [comment]
@contra Yes, I didn't start to develop this. Sorry I was busy recently. Welcome to PR! :)
