### ISSUE TITLE
Sidebar component gives error because it is not adjcent to body tag

### ISSUE THREAD

**Issue by michaelryancaputo** [jessy1092/react-semantify#27]
The error i'm getting is `Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag`

My layout render looks like this:

        return <div className='pusher'>
          <Sidebar className='theSidebar' flux={flux} init={this.state.secondaryNav}><SecondaryNavigation /></Sidebar>
          <PrimaryNavigation flux={flux} />
          <Button className='icon' style={style.hamburger} onClick={this._expandNav.bind(this)}><Icon className='sidebar icon' color='black'></Icon></Button>
          <Map flux={flux} />
          <RouteHandler flux={flux}/>
        </div>;

My router render looks like this:

    router.run(function(Handler) {
      React.render(<Handler />, document.body);
    });

Of course putting the Sidebar element outside of the initial div doesn't work because it needs to be enclosed in a container element. So what is the solution to this?

**Comment by michaelryancaputo** [comment]
For anyone else interested, I ended up finding out that I needed to change the context of my Sidebar element. This should probably be a required prop for this react component, as I don't see how anyone else would get it working otherwise.

    var init = {context: '.mainContainer'};

    return (
      <div className="mainContainer">
        <Sidebar className="theSidebar" init={init}><SecondaryNavigation /></Sidebar>
        <div className="pusher">
          <PrimaryNavigation />
          <Button className='icon' style={style.hamburger} onClick={this._expandNav}><Icon className='sidebar icon' color='black'></Icon></Button>
          <Map />
          <RouteHandler />
        </div>
      </div>
    );

**Comment by jessy1092** [comment]
@michaelryancaputo Sorry for replying late. 

You're right. On semanti-ui sidebar document, it should be set-up with that structure before initializing a sidebar.
ref. http://semantic-ui.com/modules/sidebar.html#/usage

BTW, what's the required prop mean? Use the specific structure for sidebar component?
