### ISSUE TITLE
Unable to render `Modal` because it's not a component(?)

### ISSUE THREAD

**Issue by peterbe** [jessy1092/react-semantify#30]
```
Warning: Modal(...): React component classes must extend React.Component. bundle.js:4311:10

Error: Invariant Violation: Modal.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

My code is es6 packed with webpack and I'm using **React 0.14**. 
It looks like this:

```jsx
import { Modal } from 'react-semantify';

class PersonModal extends React.Component {
  render() {
    return (
      <Modal className="examplemodal" init={true}>
        Hello
      </Modal>
    )
  }
}
```

I'm using `react-semantify` 0.3.1.

**Comment by jessy1092** [comment]
@peterbe Because it doesn't support React 0.14 now. I would start moving to react 0.14 recently. Thanks for reporting.

**Comment by peterbe** [comment]
In a sense, that's bad news because I'm stuck. The goods news is that I wasn't doing it wrong at least :)

I doubt that I'll find time resources (or knowhow) to help but if I could I would give you a hug and a six pack of your favorite drink to support.

**Comment by jessy1092** [comment]
@peterbe Ha, thank you for your hug and six pack. I could feel that when I was coding at midnight. 

The work is in hands(in branch [0.4](https://github.com/jessy1092/react-semantify/tree/0.4), but still has some problem) and I think maybe finish in this weekend.

**Comment by peterbe** [comment]
I'll try out the branch after this weekend then. By the way, how do you `npm install`

**Comment by jessy1092** [comment]
@peterbe I already release `0.4.0` for `react 0.14.x`. You can just bump version to try and test. If it has any problem. Please report to me. Thanks a lot!!!

BTW install specific branch example:
`npm install git://github.com/jessy1092/react-semantify.git#0.4`
or write in `package.json` and just type `npm install`
```json
{
   "dependencies": {
       "react-semantify": "git://github.com/jessy1092/react-semantify.git#0.4"
   }
}
```
ref: https://docs.npmjs.com/cli/install

**Comment by peterbe** [comment]
Now it's complaining about `$` not being available. 
<img width="1208" alt="screen shot 2015-11-23 at 8 07 33 am" src="https://cloud.githubusercontent.com/assets/26739/11337219/504e48f0-91b9-11e5-9929-d403f5019899.png">

**Comment by jessy1092** [comment]
@peterbe Do you import jquery with bundle file? Which build tool did you use?

I use browserify to bundle. It's ok. Just add following line in top file.
```js
import $ from 'jquery';
global.$ = global.jQuery = $;
```

BTW, I use npm for installing jquery

**Comment by peterbe** [comment]
Yes, I have jquery installed with npm. But I use webpack. I'll try that `global.$` trick.

**Comment by peterbe** [comment]
That `global.$` trick worked. 
However, now I'm getting another error:

Before I clicked to open the modal:
<img width="1208" alt="screen shot 2015-11-23 at 1 13 09 pm" src="https://cloud.githubusercontent.com/assets/26739/11345299/0a24296e-91e4-11e5-9add-1e5ebb210a64.png">

After I clicked to open the modal:
<img width="1210" alt="screen shot 2015-11-23 at 1 14 21 pm" src="https://cloud.githubusercontent.com/assets/26739/11345322/2a05c5ee-91e4-11e5-8da1-5e3c47ffbdb5.png">

The way I my app works is like this:

```jsx
class FilteredList extends React.Component {
  render() {
    let personModal = null;
    if (this.state.editPerson) {
      personModal = <PersonModal
        person={this.state.editPerson}
        onSave={this.handleCloseEditPerson.bind(this)}
        onClose={this.handleCloseEditPerson.bind(this)} />
    }
    return (
      <div>
        <div className="ui big labeled fluid left icon input">
        </div>
        <List
          onclick={this.handleClickDate.bind(this)}
          onclickPerson={this.handleClickPerson.bind(this)}
          items={items}
          lumpNames={this.state.lumpNames}/>
        {personModal}
      </div>
    );    
  }
}
ReactDOM.render(<FilteredList/>, document.getElementById('mount-point'));
```

So it seems a perfectly normal way of inserting the `PersonModal` component. It currently looks like this:

```jsx
class PersonModal extends React.Component {
  render() {
    console.log('Render PersonModal', this.props.person);
    let person = this.props.person;
    return (
      <Modal className="examplemodal" init={true}>
        Hello
      </Modal>
    )
```

Perhaps it's not a bug in `react-semantify` and just a bug in how I do React.

**Comment by jessy1092** [comment]
@peterbe There are two possible reasons.

One is react version not match.

Another is `Modal` moved. By semantic-ui [document](http://semantic-ui.com/modules/modal.html#/usage), `Modal` would be move to the root after initialization.
You could solve by rendering in the root at first. Or try to set 
```js
<Modal className="examplemodal" init={{detachable: false}}>
   Hello
</Modal>
```

**Comment by peterbe** [comment]
That didn't make any difference. (Setting `{{detachable: false}}`).

There's only one `node_modules/react/dist/react*js`. My `package.json` looks like this:

```json
...
  "dependencies": {
    "horsey": "2.6.1",
    "jquery": "2.1.4",
    "noty": "2.3.7",
    "react": "0.14.0",
    "react-dom": "0.14.0",
    "react-router": "1.0.0-rc3",
    "react-semantify": "0.4.0",
    "sugar-date": "1.5.1",
    "whatwg-fetch": "0.10.0"
  }
```

**Comment by peterbe** [comment]
Oh. I have 0.14.0 install and `react-semantify` installed 0.14.3 in `node_modules/react-semantify/node_modules/react`. :(

I changed my `package.json` to pin version 0.14.3 of react and react-dom. Now things are working better. Except I now need to get the actual semantic-ui jquery based JS code in there:

<img width="1206" alt="screen shot 2015-11-23 at 2 35 58 pm" src="https://cloud.githubusercontent.com/assets/26739/11347449/8a6d1418-91ef-11e5-9814-f621592048c7.png">

**Comment by jessy1092** [comment]
@peterbe 
Yes, you need add `semantic.js`. There are many way to get it. 
- bower
- cdn
- npm

Currently, I suggest use bower because npm install process would enter interaction mode when you use semantic 2.x . ref https://github.com/Semantic-Org/Semantic-UI/issues/1816

You can see the example on [website](https://github.com/jessy1092/react-semantify/tree/website) branch but I was using `gulp` and `browserify`. Maybe I could add the minimum examples in the future.

BTW update `react-semantify` to `0.4.1`. This version fix some ES6 export and import issue. ref [PR](https://github.com/jessy1092/react-semantify/pull/34)

**Comment by peterbe** [comment]
Yes, I got it working. I just added it globally for now. I think we're done. The bug has been solved. 

I'm wondering if other people are going to stumble on that `global.$` trick which I didn't know about.

**Comment by peterbe** [comment]
Turns out it was solved with https://github.com/jessy1092/react-semantify/issues/28
