### ISSUE TITLE
Support for Semantic-UI 2.1.5?

### ISSUE THREAD

**Issue by john-osullivan** [jessy1092/react-semantify#37]
Hello,

I'm using this library to incorporate Semantic-UI into my project, and I'm running into [a bug with integer validation](https://github.com/Semantic-Org/Semantic-UI/issues/3274) which the Semantic-UI people said got fixed in version 2.1.5.  However, I'm still running into it after updating to react-semantify at 0.4.1.  Am I doing something wrong, or does this package not depend on the most up-to-date version?

Thanks!

**Comment by jessy1092** [comment]
@john-osullivan I didn't combine `react-semantiy` version with `semantic-ui`. You can choose your `semantic-ui` version you like and update version by yourself.

**Comment by john-osullivan** [comment]
Ah, I had no idea -- thanks for the tip!
