### ISSUE TITLE
Can't use state within Modal

### ISSUE THREAD

**Issue by qpoon** [jessy1092/react-semantify#38]
Hi,

I'd like to display `{this.state.someValue}` within a `<Modal>` I'm showing. Unfortunately React throws a
```
Uncaught Invariant Violation: findComponentRoot(..., .0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```
... likely because Semantic/jQuery wraps the dimmer screen around the actual modal div that owns the `data-reactid`, and that throws React off when `this.state.someValue` is updated and it tries to re-render.

I'm not sure what the best solution would look like. Do you think jQuery's `modal` function could be ported over to React so it won't muck up the DOM?

**Comment by mscolnick** [comment]
Not the best solution if your page is tall and scrolls. But you can set `detachable: false` when you initialize the modal. This error is thrown because once you initialize the modal, it gets moved to the top of the DOM. This will prevent it from moving then react can find the component (but then doesnt scroll with the page).

**Comment by jessy1092** [comment]
Yes, @mscolnick is correct.

The other way is just render modal on the top of the DOM directly. Ex. render on `custom_modal`.
```html
<body>
  <div id="custom_modal" class="ui dimmer modals"></div>
</body>
```

**Comment by qpoon** [comment]
Thanks! I ended up creating a new react component:

```jsx
      <div className={"ui dimmer modals page transition " + (this.state.isActive ? "active visible" : "hidden")} style={{display: "block"}}>
        <div
          className={"ui modal transition " + (this.state.isActive ? "active visible" : "hidden")}
          ref="modalBox"
          style={{marginTop: this.state.halfHeight}}>
          <i className="close icon" onClick={this.hide} />
          {this.props.children}
        </div>
      </div>
```
