### ISSUE TITLE
Misspelling in title of page

### ISSUE THREAD

**Issue by Hectim** [jessy1092/react-semantify#41]
Just a heads up, the in the title of your github.io page it says **Semantiy** instead of **Semantify**.

Because of this, if you were to google _semantic ui integration with react_, you come up as the fourth link but it says Semantiy. 

And I don't think this one in particular is pull request-able (grep came up dry), sorry.

**Comment by jessy1092** [comment]
@Hectim Thanks a lot!!!!! Actually website source code is no `website` branch. It would be deployed on `gh-pages` automatically. :smile:
