### ISSUE TITLE
Unable to provide id attribute to react-semantify components

### ISSUE THREAD

**Issue by austinfox** [jessy1092/react-semantify#43]
Ideal definition:
`<Divider id="my-special-id" />`
Ideal result:
`<div id="my-special-id" class="ui divider" data-reactid=".1.1.1"></div>`
Current result:
`<div class="ui divider" data-reactid=".1.1.1"></div>`

If I use the equivalent react component for a div and provide it an id, the id is respected:
Current definition:
`<div id="my-special-id" className="ui divider" />`
Current result:
`<div id="my-special-id" class="ui divider" data-reactid=".1.1.1"></div>`

**Comment by jessy1092** [comment]
@austinfox Thanks for catching. It would be fixed on next version.

**Comment by austinfox** [comment]
Thanks for fixing this!

**Comment by jessy1092** [comment]
@austinfox I landed on `v0.4.2`. Could you help to test? Thanks a lot. :)

**Comment by austinfox** [comment]
@jessy1092 sure
