### ISSUE TITLE
radio input

### ISSUE THREAD

**Issue by cordoval** [jessy1092/react-semantify#51]
I need this depserately please let me know if it is on the way

http://semantic-ui.com/modules/checkbox.html#radio

**Comment by jessy1092** [comment]
Thank for request. I refactor `react-semantify` recently for adding properties easily.

May you please write some suggestions for `checkbox`?

Maybe:
```js
<Checkbox type="radio">
	<input checked="checked" type="radio"/>
	<label>Radio</label>
</Checkbox>
```

or hide the input element:
```js
<Checkbox type="radio" checked={true}>Radio</Checkbox>
```

or others way that you like. :)

**Comment by cordoval** [comment]
we built our own radio component

**Comment by cordoval** [comment]
thanks though, i will check again seminatify
