### ISSUE TITLE
modules: modal.js

### ISSUE THREAD

**Issue by ZachBergh** [jessy1092/react-semantify#52]
$ is not defined

Have no $ object.

￼
<img width="494" alt="d51b203c-8a91-4306-b278-2b8128cc2474" src="https://cloud.githubusercontent.com/assets/4055314/14735811/bf706d40-08a5-11e6-88c9-ac8d4a92cb51.png">
<img width="812" alt="7383729a-bfd1-4ac6-affe-fd24670b7388" src="https://cloud.githubusercontent.com/assets/4055314/14735810/beb8d676-08a5-11e6-9b9b-d5515b186321.png">

**Comment by jessy1092** [comment]
@ZachBergh You should include jquery library for dependency.

**Comment by ZachBergh** [comment]
Fixed, thanks a lot.

Found out is my gulp file have some problem with Jquery's loading.
