### ISSUE TITLE
Create "buttons" component

### ISSUE THREAD

**Issue by markelog** [jessy1092/react-semantify#53]
Otherwise you have to use your own `div` wrapper by meshing semantic components and html.

Would it makes sense?

**Comment by jessy1092** [comment]
Use `<Buttons></Buttons>` to implement Button's Group Variations ? I think it is a good idea!!

Like:
```jsx
<Buttons className="basic">
  <Button>One</Button>
  <Button>Two</Button>
  <Button>Three</Button>
</Buttons>
```

**Comment by b0gok** [comment]
+1

**Comment by b0gok** [comment]
Check this, please https://github.com/jessy1092/react-semantify/pull/77

**Comment by b0gok** [comment]
@jessy1092 ✋

**Comment by jessy1092** [comment]
publish on `v0.6.0` thanks @b0gok :)
