### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by tomitrescak** [jessy1092/react-semantify#54]
Hi, how do you load icons please? I get only "square" placeholders caliming that woff and woff2 files are missing. Thanks

**Comment by jessy1092** [comment]
@tomitrescak How do you include semantic-ui? There are many ways to load icons with woff and woff2.

If you use through `bower`. You need to copy source file into your project.
`bower_components/semantic-ui/src/themes/default/assets/**/*` copy to `themes/default/assets/`

Use gulp to copy:
```js
gulp.task('styles-assets', () => {
  return gulp.src('./bower_components/semantic-ui/src/themes/default/assets/**/*')
    .pipe(gulp.dest(`${BUILD_PATH}/themes/default/assets/`));
});
```

**Comment by tomitrescak** [comment]
@jessy1092 yes, this seems like the only possible way. Was wondering if that can be automated on the package level. But, this is good enough ;)
