### ISSUE TITLE
Modal: callback event

### ISSUE THREAD

**Issue by ZachBergh** [jessy1092/react-semantify#56]
```
$('.ui.modal.myModal').modal({
        onHide: function(){
            console.log('hidden');

        },
        onShow: function(){
            console.log('shown');
        },
        onApprove: function() {
            console.log('Approve');
            return validateModal()
        }
    }).modal('show');
```

Have no callback functions ?

**Comment by ZachBergh** [comment]
use `$(".ui.modal").modal("show");` in parent component fixed.

but can we have a interface to set show or hide?

**Comment by jessy1092** [comment]
@ZachBergh You can use 

```jsx
<Modal init='show'></Modal>
```

to set show or hide. It would trigger `$('.ui.modal').modal('show');` when `componentDidMount`.
ref.
https://github.com/jessy1092/react-semantify/blob/master/docs/Modules.md#example-4

From now on, it has no way to set callback function. Maybe we should have new properties.
