### ISSUE TITLE
Input with label is not showing properly ?

### ISSUE THREAD

**Issue by sahilpandya** [jessy1092/react-semantify#57]
How to write code for input with left and right label or icon, It is not showing correct this time with react semantify, If I am doing something wrong in this below code then reply me to correct one: 

           <div className="ui left icon input loading">
                <Input placeholder="Loading..." type="text"/>
                <Icon className="search"></Icon>
            </div>
           ` <div className="ui labeled input">
                <a className="ui label">
                Label
                </a>
                <Input type="text" placeholder="Placeholder..."/>
            </div>`

**Comment by jessy1092** [comment]
@sahilpandya 
My test is ok:
```jsx
<Input className="left icon loading">
    <input placeholder="Search..." type="text" />
    <Icon className="search"></Icon>
</Input>
```
It would like:
![_2016-05-01t06-46-03 346z](https://cloud.githubusercontent.com/assets/4408071/14940511/8a837534-0fab-11e6-939f-983b85ecf105.png)

Which `semantic-ui` and `react-semantify` version did you use?

**Comment by sahilpandya** [comment]
Thanks, It is working for me.

I have one doubt related to semantic check-box input type, some time check-box input click is not working, Is there any specific reason for these,  ?

**Comment by jessy1092** [comment]
@sahilpandya I not sure but you can use `<Checkbox />` component for check-box input.

like
```jsx
<Checkbox init={true}>
	<input type="checkbox"/>
	<label>
		The Simple Checkbox
	</label>
</Checkbox>
```

ref: 
http://jessy1092.github.io/react-semantify/#/Checkbox

**Comment by sahilpandya** [comment]
Thanks, it is working correctly.
