### ISSUE TITLE
Create web site.

### ISSUE THREAD

**Issue by jessy1092** [jessy1092/react-semantify#6]
The Components' README. Like Semantic-UI web site style.

**Comment by jessy1092** [comment]
Now, the website can auto deploy by travis-ci.
If anyone want to help website, it is very helpful and welcome.
The website source code is in the [website](https://github.com/jessy1092/react-semantify/tree/website) branch

**Comment by FoxxMD** [comment]
:+1: I'd like to help. Your library is super helpful!

**Comment by jessy1092** [comment]
@FoxxMD Thank you for your praise. I create #11 for tracing document. Please feel free to pr. :+1:
