### ISSUE TITLE
Buttons on a modal do not fire onClick event

### ISSUE THREAD

**Issue by davewthompson** [jessy1092/react-semantify#63]
Buttons on a Modal object don't fire the onClick event even when they are clicked.

Relatively easy to replicate - create a modal dialog and put a button on it and try and click it.

**Comment by davewthompson** [comment]
Looking into the code a little more, it appears the Modal object's transitions break React. The transitions disconnect child elements from the DOM and then reconnect them in another place - I'm not sure if this can be fixed without rewriting large parts of the Modal's code.

**Comment by jessy1092** [comment]
@davewthompson By semantic-ui [document](http://semantic-ui.com/modules/modal.html#/usage), Modal would be move to the root after initialization.
You could solve by rendering in the root at first. Or try to set

```jsx
<Modal className="examplemodal" init={{detachable: false}}>
   Hello
</Modal>
```

**Comment by davewthompson** [comment]
@jessy1092 - thank you - I shall try that!
