### ISSUE TITLE
unknown prop error on react 15.2.0

### ISSUE THREAD

**Issue by volodyad** [jessy1092/react-semantify#66]
With react 15.2.0 version we have got the new warning - https://facebook.github.io/react/warnings/unknown-prop.html 
At the moment there is definetley error in dropdown component cause in Dropdown render 
``` <div {...other} className={className} ref="dropdown" >
        {children}
      </div>```
you pass other prop which in my case contains init, and init is not allowed react prop for div component

**Comment by geonerd81** [comment]
I am also seeing [(https://facebook.github.io/react/warnings/unknown-prop.html )] same issue, mainly with init tag, in react 15.2.1

**Comment by hlehmann** [comment]
same issue, same reason

**Comment by jessy1092** [comment]
I publish v0.5.2 to fix this problem. Please help to verify. :)
