### ISSUE TITLE
<Button onClick={does not work}...

### ISSUE THREAD

**Issue by hipertracker** [jessy1092/react-semantify#7]
How to pass own handler to onClick event inside in Button component? The way it is implemented shows that I cannot use my handler unless I extend somehow Button class to provide my own onClick method.  When I remove the line "onClick={this.onClick}" from elements/button.jsx than I am free to use my own handlers. The unit test fore button.jsx is wrong. It does not test anything for onClick. The passed handler is never excuted.

**Comment by jessy1092** [comment]
Sorry, my fault. You're right. The onClick function should be on <Unit> component test.
It didn't trigger on element.

**Comment by jessy1092** [comment]
v0.2.1: some elements onClick function not work.
- Segment, Label, Icon, Header, Flag, Button

**Comment by jessy1092** [comment]
@hipertracker  Thanks. It should be working on v0.2.2  :smile:
